### ISSUE TITLE
Live demo and the examples are not working

### ISSUE THREAD

**Issue by idtoufik** [colyseus/colyseus-examples#14]
Hi,
I have tried the instructions that I have found on the readme to set up the project but it doesn't seem to work I'm getting connection refused error when I access [http://localhost:2657/](http://localhost:2657/), also I have tried the heroku live demo I think that it is also not working I'm getting a lot of errors in the browser console.
My node server version is 10.15.1
Thanks

**Comment by Tobi4s1337** [comment]
Hey @idtoufik ,
please try to open the following link in your browser after you started your local server:
http://localhost:2567/
Then it should be working =)
(Seems like there is a typo somewhere)

**Comment by idtoufik** [comment]
Don't know why but it works now, I have followed the same steps before submitting this issue.
Thank you.

**Comment by IanMayo** [comment]
@idtoufik - I'm pretty sure you mis-typed the port number, the 6 and 5 are reversed in your comment.

Here's what I see:
![image](https://user-images.githubusercontent.com/1108513/52349513-a361ec80-2a1e-11e9-8209-edaad9f2cc76.png)

**Comment by idtoufik** [comment]
thank you for your remark.
I was sure that I didn't make any port number error because I have clicked on the link that I have found in the readme file, it appears that the link present in the readme "http://localhost:2567" redirects to "http://localhost:2657" can you please fix this.
Thanks

**Comment by IanMayo** [comment]
Hey - that was cryptic - well spotted.

How about having a go at fixing it.  Just click on the "Edit" button at the top-right of the `README.md` file:
![image](https://user-images.githubusercontent.com/1108513/52350474-97772a00-2a20-11e9-8652-09b90299688b.png)

**Comment by IanMayo** [comment]
Here is where the problem arose, it was an edit made 30 minutes ago:
![image](https://user-images.githubusercontent.com/1108513/52350941-8c70c980-2a21-11e9-9c76-89b070744830.png)

https://github.com/colyseus/colyseus-examples/commit/9d6be7bd05470a8064cc740cf83d01fd9283ca38#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by idtoufik** [comment]
Ok thanks, I didn't have the rights otherwise I did it my self.

**Comment by IanMayo** [comment]
@idtoufik = you don't need write access to this repo to do it, the change happens in a forked repo.

I just made the change - it took seconds:
https://github.com/colyseus/colyseus-examples/pull/15

**Comment by Tobi4s1337** [comment]
> 
> 
> @idtoufik = you don't need write access to this repo to do it, the change happens in a forked repo.
> 
> I just made the change - it took seconds:
> #15

Oh that is definitely good to know. (Also did not know about this before)

**Comment by idtoufik** [comment]
sorry I didn't see your comments.
