### ISSUE TITLE
room.state.players.onRemove is never called

### ISSUE THREAD

**Issue by dogwatch** [colyseus/colyseus-examples#20]
1) Open two tabs with http://localhost:2567/02-state-handler.html
2) Look https://i.imgur.com/j7Wlnpm.png
3) Close one of the tabs.
4) Look https://i.imgur.com/1Y6L0sM.png

Instead of room.state.players.onRemove, called room.state.players.onAdd without a second argument.

Node v13.0.1

**Comment by endel** [comment]
Hi @dogwatch, thanks for reporting, It was a versioning issue. The [`colyseus.js` distribution file](https://github.com/colyseus/colyseus.js/blob/master/dist/colyseus.js) wasn't updated, and the module versions of this repo wasn't the latest ones. Cheers!
