### ISSUE TITLE
Is there a reconnection mechanism for network disconnection

### ISSUE THREAD

**Issue by xingwen93** [colyseus/colyseus-examples#22]
Is there a reconnection mechanism for network disconnection

**Comment by seiyria** [comment]
Yes, users reconnect automatically when they disconnect (generally). This really belongs on colyseus' main tracker, though, not this one. If you still need help please ask and re-open there.

**Comment by endel** [comment]
You're probably looking for `allowReconnection` / `client.reconnect()`
https://docs.colyseus.io/server/room/#allowreconnection-client-seconds
