### ISSUE TITLE
Does colyseus's document have a document corresponding to another version?

### ISSUE THREAD

**Issue by xingwen93** [colyseus/colyseus-examples#23]
Does colyseus's document have a document corresponding to another version?

**Comment by endel** [comment]
Only the latest version is available on https://docs.colyseus.io/
For 0.10 only navigating on the repository's history: 
(this is the latest version before 0.11) https://github.com/colyseus/docs/tree/e37c2eb7f4f0dc233edb863cc4359d1627436ef6

I'd recommend upgrading to 0.11 if you can. Version 0.12 is coming soon (mostly no breaking changes in comparison to 0.11)

**Comment by xingwen93** [comment]
Ths

**Comment by xingwen93** [comment]
Very Good!
