### ISSUE TITLE
Continuously unable to deploy my server to heroku

### ISSUE THREAD

**Issue by Roeefl** [colyseus/colyseus-examples#27]
Just a small question for now, please, I just don't get something.

You've defined
```
"heroku-postbuild": "npm run build"
```

in your scripts.

And it deploys to Heroku successfully even though a build script is not specified. 

When I try to do the same thing (I mean literally the same project with a different name and Room file), Heroku would complain that a build script is missing (which it does - I get it).

How does that happen?

Thank you

**Comment by endel** [comment]
That's a good question, I think this is a left over from previous versions, can't really explain why my builds are not broken, if you remove the `heroku-postbuild` step it should work!
