### ISSUE TITLE
Client using preview and as of this date picks up colyseus 16.x, server using 15.x

### ISSUE THREAD

**Issue by MikalDev** [colyseus/colyseus-examples#34]
Client using preview and as of this date picks up colyseus 16.x, server using 15.x

Should sync client and server coly versions.

In my fork, I ended up using: https://unpkg.com/colyseus.js@0.15.26/dist/colyseus.js and the state handler example now works.

**Comment by endel** [comment]
Thank you for noticing and raising the issue @MikalDev 🙏
